export const siteTaskDefinitions = [
  {
    key: 'listing',
    label: 'Content',
    route: '/listing',
    description: 'Curated platform updates and discoverable content.',
    contentType: 'listing',
    enabled: false,
  },
  {
    key: 'classified',
    label: 'Content',
    route: '/classified',
    description: 'Curated platform updates and discoverable content.',
    contentType: 'classified',
    enabled: false,
  },
  {
    key: 'article',
    label: 'Content',
    route: '/article',
    description: 'Curated platform updates and discoverable content.',
    contentType: 'article',
    enabled: true,
  },
  {
    key: 'image',
    label: 'Content',
    route: '/image',
    description: 'Curated platform updates and discoverable content.',
    contentType: 'image',
    enabled: false,
  },
  {
    key: 'profile',
    label: 'Content',
    route: '/profile',
    description: 'Curated platform updates and discoverable content.',
    contentType: 'profile',
    enabled: false,
  },
  {
    key: 'sbm',
    label: 'Content',
    route: '/sbm',
    description: 'Curated platform updates and discoverable content.',
    contentType: 'sbm',
    enabled: false,
  },
  {
    key: 'comment',
    label: 'Content',
    route: '/blog',
    description: 'Curated platform updates and discoverable content.',
    contentType: 'comment',
    enabled: false,
  },
  {
    key: 'pdf',
    label: 'Content',
    route: '/pdf',
    description: 'Curated platform updates and discoverable content.',
    contentType: 'pdf',
    enabled: false,
  },
  {
    key: 'org',
    label: 'Content',
    route: '/team',
    description: 'Curated platform updates and discoverable content.',
    contentType: 'org',
    enabled: false,
  },
] as const

export const siteTaskViews = {
  listing: '/listing',
  classified: '/classified',
  article: '/article',
  image: '/image',
  profile: '/profile',
  social: '/community',
  sbm: '/sbm',
  comment: '/blog',
  pdf: '/pdf',
  org: '/team',
} as const
